//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Restier.Scaffolding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Restier.Scaffolding.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon @__TemplateIcon {
            get {
                object obj = ResourceManager.GetObject("__TemplateIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _TemplateIconSample {
            get {
                object obj = ResourceManager.GetObject("_TemplateIconSample", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Config.
        /// </summary>
        public static string AddConfigWindowTitle {
            get {
                return ResourceManager.GetString("AddConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data context....
        /// </summary>
        public static string AddNewDbContext {
            get {
                return ResourceManager.GetString("AddNewDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} must be non-empty and non-null..
        /// </summary>
        public static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeButtonText {
            get {
                return ResourceManager.GetString("ChangeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Config name.
        /// </summary>
        public static string ConfigNameLabel {
            get {
                return ResourceManager.GetString("ConfigNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Data context class:.
        /// </summary>
        public static string DataContextClassLabel {
            get {
                return ResourceManager.GetString("DataContextClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller name must be non-empty..
        /// </summary>
        public static string EmptyControllerName {
            get {
                return ResourceManager.GetString("EmptyControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database context type name must be non-empty..
        /// </summary>
        public static string EmptyDbContextName {
            get {
                return ResourceManager.GetString("EmptyDbContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name must be non-empty..
        /// </summary>
        public static string EmptyModelName {
            get {
                return ResourceManager.GetString("EmptyModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file &apos;{0}&apos;..
        /// </summary>
        public static string FailedToOpenFile {
            get {
                return ResourceManager.GetString("FailedToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0} in project directory. .
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more than one {0} in project directory..
        /// </summary>
        public static string FilesFoundMore {
            get {
                return ResourceManager.GetString("FilesFoundMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller name is invalid..
        /// </summary>
        public static string InvalidControllerName {
            get {
                return ResourceManager.GetString("InvalidControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is not allowed to contain any of these characters: {0}.
        /// </summary>
        public static string InvalidIdentifierCharacters {
            get {
                return ResourceManager.GetString("InvalidIdentifierCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid because it is empty..
        /// </summary>
        public static string InvalidIdentifierEmpty {
            get {
                return ResourceManager.GetString("InvalidIdentifierEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid because it is a reserved name..
        /// </summary>
        public static string InvalidIdentifierReservedName {
            get {
                return ResourceManager.GetString("InvalidIdentifierReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid because it has white spaces..
        /// </summary>
        public static string InvalidIdentifierWhitespaces {
            get {
                return ResourceManager.GetString("InvalidIdentifierWhitespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project does not contain a valid {0}, which will be used in scaffolding. Please add a valid {0} first..
        /// </summary>
        public static string InvalidResource {
            get {
                return ResourceManager.GetString("InvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Layout Page.
        /// </summary>
        public static string LayoutPageSelectorHeading {
            get {
                return ResourceManager.GetString("LayoutPageSelectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Pages (*.cshtml)|*.cshtml.
        /// </summary>
        public static string MasterPageCsHtmlFilter {
            get {
                return ResourceManager.GetString("MasterPageCsHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Pages (*.vbhtml)|*.vbhtml.
        /// </summary>
        public static string MasterPageVbHtmlFilter {
            get {
                return ResourceManager.GetString("MasterPageVbHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data _context type:.
        /// </summary>
        public static string NewDataContextLabel {
            get {
                return ResourceManager.GetString("NewDataContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data Context.
        /// </summary>
        public static string NewDataContextWindowTitle {
            get {
                return ResourceManager.GetString("NewDataContextWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        ///more details see {0}..
        /// </summary>
        public static string OverpostingWarningMessage {
            get {
                return ResourceManager.GetString("OverpostingWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name {0} already exists. Do you want to replace it?.
        /// </summary>
        public static string OverwriteMessage {
            get {
                return ResourceManager.GetString("OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An OData Restier scaffolder .
        /// </summary>
        public static string RestierScaffolderDescription {
            get {
                return ResourceManager.GetString("RestierScaffolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicrosoftODataRestierScaffoler.
        /// </summary>
        public static string RestierScaffolderId {
            get {
                return ResourceManager.GetString("RestierScaffolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft OData Restier Scaffoler.
        /// </summary>
        public static string RestierScaffolderName {
            get {
                return ResourceManager.GetString("RestierScaffolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Scaffold_Auther {
            get {
                return ResourceManager.GetString("Scaffold_Auther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project language is not supported..
        /// </summary>
        public static string ScaffoldLanguageNotSupported {
            get {
                return ResourceManager.GetString("ScaffoldLanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web API configuration must be updated during the scaffolding. Please go to the configuration class to check the details. .
        /// </summary>
        public static string ScaffoldODataReadMeText {
            get {
                return ResourceManager.GetString("ScaffoldODataReadMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file is missing from the installed template folder..
        /// </summary>
        public static string VersionsFileMissing {
            get {
                return ResourceManager.GetString("VersionsFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only available for views with a strongly-typed model..
        /// </summary>
        public static string ViewWithoutModelTooltip {
            get {
                return ResourceManager.GetString("ViewWithoutModelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WebApi config class:.
        /// </summary>
        public static string WebApiConfigNameLabel {
            get {
                return ResourceManager.GetString("WebApiConfigNameLabel", resourceCulture);
            }
        }
    }
}
