//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.OData.Design.Scaffolding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.OData.Design.Scaffolding.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon @__TemplateIcon {
            get {
                object obj = ResourceManager.GetObject("__TemplateIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _TemplateIconSample {
            get {
                object obj = ResourceManager.GetObject("_TemplateIconSample", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Controller.
        /// </summary>
        public static string AddControllerWindowTitle {
            get {
                return ResourceManager.GetString("AddControllerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data context....
        /// </summary>
        public static string AddNewDbContext {
            get {
                return ResourceManager.GetString("AddNewDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} must be non-empty and non-null..
        /// </summary>
        public static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Entity Framework 6 or greater to use async controller actions..
        /// </summary>
        public static string AsyncControllerActionsHelpLabel {
            get {
                return ResourceManager.GetString("AsyncControllerActionsHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use _async controller actions.
        /// </summary>
        public static string AsyncControllerActionsLabel {
            get {
                return ResourceManager.GetString("AsyncControllerActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string BrowseFiles {
            get {
                return ResourceManager.GetString("BrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a layout page.
        /// </summary>
        public static string ChooseLayoutPage {
            get {
                return ResourceManager.GetString("ChooseLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Controller name.
        /// </summary>
        public static string ControllerNameLabel {
            get {
                return ResourceManager.GetString("ControllerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Data context class:.
        /// </summary>
        public static string DataContextClassLabel {
            get {
                return ResourceManager.GetString("DataContextClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller name must be non-empty..
        /// </summary>
        public static string EmptyControllerName {
            get {
                return ResourceManager.GetString("EmptyControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database context type name must be non-empty..
        /// </summary>
        public static string EmptyDbContextName {
            get {
                return ResourceManager.GetString("EmptyDbContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name must be non-empty..
        /// </summary>
        public static string EmptyModelName {
            get {
                return ResourceManager.GetString("EmptyModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name must be non-empty..
        /// </summary>
        public static string EmptyTemplateName {
            get {
                return ResourceManager.GetString("EmptyTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View name must be non-empty..
        /// </summary>
        public static string EmptyViewName {
            get {
                return ResourceManager.GetString("EmptyViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file &apos;{0}&apos;..
        /// </summary>
        public static string FailedToOpenFile {
            get {
                return ResourceManager.GetString("FailedToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate _views.
        /// </summary>
        public static string GenerateViewsCheckLabel {
            get {
                return ResourceManager.GetString("GenerateViewsCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller name is invalid..
        /// </summary>
        public static string InvalidControllerName {
            get {
                return ResourceManager.GetString("InvalidControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is not allowed to contain any of these characters: {0}.
        /// </summary>
        public static string InvalidIdentifierCharacters {
            get {
                return ResourceManager.GetString("InvalidIdentifierCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid because it is empty..
        /// </summary>
        public static string InvalidIdentifierEmpty {
            get {
                return ResourceManager.GetString("InvalidIdentifierEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid because it is a reserved name..
        /// </summary>
        public static string InvalidIdentifierReservedName {
            get {
                return ResourceManager.GetString("InvalidIdentifierReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid because it has white spaces..
        /// </summary>
        public static string InvalidIdentifierWhitespaces {
            get {
                return ResourceManager.GetString("InvalidIdentifierWhitespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Leave empty if it is set in a Razor __viewstart file).
        /// </summary>
        public static string LayoutPageInstructionsLabel {
            get {
                return ResourceManager.GetString("LayoutPageInstructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Layout Page.
        /// </summary>
        public static string LayoutPageSelectorHeading {
            get {
                return ResourceManager.GetString("LayoutPageSelectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Pages (*.cshtml)|*.cshtml.
        /// </summary>
        public static string MasterPageCsHtmlFilter {
            get {
                return ResourceManager.GetString("MasterPageCsHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Pages (*.vbhtml)|*.vbhtml.
        /// </summary>
        public static string MasterPageVbHtmlFilter {
            get {
                return ResourceManager.GetString("MasterPageVbHtmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Model class:.
        /// </summary>
        public static string ModelClassLabel {
            get {
                return ResourceManager.GetString("ModelClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data _context type:.
        /// </summary>
        public static string NewDataContextLabel {
            get {
                return ResourceManager.GetString("NewDataContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data Context.
        /// </summary>
        public static string NewDataContextWindowTitle {
            get {
                return ResourceManager.GetString("NewDataContextWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type &apos;{0}&apos; has no key defined. Define a key for this entity type..
        /// </summary>
        public static string NoKeyDefinedError {
            get {
                return ResourceManager.GetString("NoKeyDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name {0} already exists. Do you want to replace it?.
        /// </summary>
        public static string OverwriteMessage {
            get {
                return ResourceManager.GetString("OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reference script libraries.
        /// </summary>
        public static string ReferenceScriptLibrariesCheckLabel {
            get {
                return ResourceManager.GetString("ReferenceScriptLibrariesCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string Scaffold_Auther {
            get {
                return ResourceManager.GetString("Scaffold_Auther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project language is not supported..
        /// </summary>
        public static string ScaffoldLanguageNotSupported {
            get {
                return ResourceManager.GetString("ScaffoldLanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A OData V4 (http://odata.github.io/) Web API 2 controller with CRUD actions to create, read, update, delete, and list entities..
        /// </summary>
        public static string ScaffoldODataActions_Description {
            get {
                return ResourceManager.GetString("ScaffoldODataActions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODataV4ControllerWithActionsScaffolder.
        /// </summary>
        public static string ScaffoldODataActions_Id {
            get {
                return ResourceManager.GetString("ScaffoldODataActions_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OData V4 Web API Controller.
        /// </summary>
        public static string ScaffoldODataActions_Name {
            get {
                return ResourceManager.GetString("ScaffoldODataActions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebApiConfig class may require additional changes to add a route for this controller. Merge these statements into the Register method of the WebApiConfig class as applicable. Note that OData URLs are case sensitive..
        /// </summary>
        public static string ScaffoldODataModificationMessage {
            get {
                return ResourceManager.GetString("ScaffoldODataModificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web API configuration must be updated for each OData controller created by scaffolding. Instructions are available in the generated controller..
        /// </summary>
        public static string ScaffoldODataReadMeText {
            get {
                return ResourceManager.GetString("ScaffoldODataReadMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a layout page.
        /// </summary>
        public static string SpecifyLayoutPage {
            get {
                return ResourceManager.GetString("SpecifyLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Use a layout page:.
        /// </summary>
        public static string UseLayoutPageCheckLabel {
            get {
                return ResourceManager.GetString("UseLayoutPageCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file is missing from the installed template folder..
        /// </summary>
        public static string VersionsFileMissing {
            get {
                return ResourceManager.GetString("VersionsFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views:.
        /// </summary>
        public static string ViewsLabel {
            get {
                return ResourceManager.GetString("ViewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (without model).
        /// </summary>
        public static string ViewTemplateWithoutModel {
            get {
                return ResourceManager.GetString("ViewTemplateWithoutModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only available for views with a strongly-typed model..
        /// </summary>
        public static string ViewWithoutModelTooltip {
            get {
                return ResourceManager.GetString("ViewWithoutModelTooltip", resourceCulture);
            }
        }
    }
}
