//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 08.03.2021 19:52:41
namespace Microsoft.OData.Service.Sample.TrippinInMemory.Models
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    internal partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<Person>("People");
                }
                return this._People;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Person> _People;
        /// <summary>
        /// There are no comments for Airlines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Airline> Airlines
        {
            get
            {
                if ((this._Airlines == null))
                {
                    this._Airlines = base.CreateQuery<Airline>("Airlines");
                }
                return this._Airlines;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Airline> _Airlines;
        /// <summary>
        /// There are no comments for Airports in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Airport> Airports
        {
            get
            {
                if ((this._Airports == null))
                {
                    this._Airports = base.CreateQuery<Airport>("Airports");
                }
                return this._Airports;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Airport> _Airports;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
        /// <summary>
        /// There are no comments for Airlines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual void AddToAirlines(Airline airline)
        {
            base.AddObject("Airlines", airline);
        }
        /// <summary>
        /// There are no comments for Airports in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual void AddToAirports(Airport airport)
        {
            base.AddObject("Airports", airport);
        }
        /// <summary>
        /// There are no comments for Me in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual PersonSingle Me
        {
            get
            {
                if ((this._Me == null))
                {
                    this._Me = new PersonSingle(this, "Me");
                }
                return this._Me;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private PersonSingle _Me;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"" Version=""4.0"">
  <edmx:DataServices>
    <Schema xmlns=""http://docs.oasis-open.org/odata/ns/edm"" Namespace=""Microsoft.OData.Service.Sample.TrippinInMemory.Models"">
      <EntityType Name=""Person"">
        <Key>
          <PropertyRef Name=""UserName"" />
        </Key>
        <Property Name=""UserName"" Nullable=""false"" Type=""Edm.String"" />
        <Property Name=""Gender"" Nullable=""false"" Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender"" />
        <Property Name=""Age"" Type=""Edm.Int64"" />
        <Property Name=""HomeAddress"" Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Location"" />
        <NavigationProperty Name=""Friends"" Type=""Collection(Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person)"" />
        <NavigationProperty Name=""Trips"" Type=""Collection(Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip)"" />
      </EntityType>
      <EntityType Name=""Airline"">
        <Key>
          <PropertyRef Name=""AirlineCode"" />
        </Key>
        <Property Name=""AirlineCode"" Nullable=""false"" Type=""Edm.String"" />
        <Property Name=""Name"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""Airport"">
        <Key>
          <PropertyRef Name=""IcaoCode"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""IcaoCode"" Nullable=""false"" Type=""Edm.String"" />
      </EntityType>
      <ComplexType Name=""Location"">
        <Property Name=""Address"" Type=""Edm.String"" />
        <Property Name=""City"" Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.City"" />
      </ComplexType>
      <ComplexType Name=""City"">
        <Property Name=""Name"" Type=""Edm.String"" />
      </ComplexType>
      <EntityType Name=""Trip"">
        <Key>
          <PropertyRef Name=""TripId"" />
        </Key>
        <Property Name=""TripId"" Nullable=""false"" Type=""Edm.Int32"" />
        <Property Name=""Name"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""Flight"" BaseType=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.PublicTransportation"">
        <Property Name=""FlightNumber"" Type=""Edm.String"" />
        <NavigationProperty Name=""Airline"" Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline"" />
        <NavigationProperty Name=""From"" Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport"" />
        <NavigationProperty Name=""To"" Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport"" />
      </EntityType>
      <EntityType Name=""Employee"" BaseType=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person"">
        <Property Name=""Cost"" Nullable=""false"" Type=""Edm.Int64"" />
        <NavigationProperty Name=""Peers"" Type=""Collection(Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person)"" />
      </EntityType>
      <EnumType Name=""PersonGender"">
        <Member Name=""Male"" Value=""0"" />
        <Member Name=""Female"" Value=""1"" />
        <Member Name=""Unknow"" Value=""2"" />
      </EnumType>
      <Function Name=""GetPersonWithMostFriends"">
        <ReturnType Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person"" />
      </Function>
      <Function Name=""GetNearestAirport"">
        <Parameter Name=""lat"" Nullable=""false"" Type=""Edm.Double"" />
        <Parameter Name=""lon"" Nullable=""false"" Type=""Edm.Double"" />
        <ReturnType Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport"" />
      </Function>
      <Action Name=""ResetDataSource"" />
      <EntityContainer Name=""Container"">
        <EntitySet Name=""People"" EntityType=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person"">
          <NavigationPropertyBinding Target=""People"" Path=""Friends"" />
        </EntitySet>
        <EntitySet Name=""Airlines"" EntityType=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline"" />
        <EntitySet Name=""Airports"" EntityType=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport"" />
        <Singleton Name=""Me"" Type=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person"" />
        <FunctionImport Name=""GetPersonWithMostFriends"" EntitySet=""People"" Function=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.GetPersonWithMostFriends"" />
        <FunctionImport Name=""GetNearestAirport"" EntitySet=""Airports"" Function=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.GetNearestAirport"" />
        <ActionImport Name=""ResetDataSource"" Action=""Microsoft.OData.Service.Sample.TrippinInMemory.Models.ResetDataSource"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

        }
        /// <summary>
        /// There are no comments for GetPersonWithMostFriends in the schema.
        /// </summary>
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle GetPersonWithMostFriends()
        {
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle(this.CreateFunctionQuerySingle<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person>("", "GetPersonWithMostFriends", false));
        }
        /// <summary>
        /// There are no comments for GetNearestAirport in the schema.
        /// </summary>
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle GetNearestAirport(double lat, double lon)
        {
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle(this.CreateFunctionQuerySingle<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport>("", "GetNearestAirport", false, new global::Microsoft.OData.Client.UriOperationParameter("lat", lat),
                    new global::Microsoft.OData.Client.UriOperationParameter("lon", lon)));
        }
        /// <summary>
        /// There are no comments for ResetDataSource in the schema.
        /// </summary>
        public virtual global::Microsoft.OData.Client.DataServiceActionQuery ResetDataSource()
        {
            return new global::Microsoft.OData.Client.DataServiceActionQuery(this, this.BaseUri.OriginalString.Trim('/') + "/ResetDataSource");
        }
    }
    /// <summary>
    /// There are no comments for PersonSingle in the schema.
    /// </summary>
    internal partial class PersonSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Person>
    {
        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) { }

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) { }

        /// <summary>
        /// Initialize a new PersonSingle object.
        /// </summary>
        public PersonSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Person> query)
            : base(query) { }

        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _Friends;
        /// <summary>
        /// There are no comments for Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> Trips
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Trips == null))
                {
                    this._Trips = Context.CreateQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip>(GetPath("Trips"));
                }
                return this._Trips;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> _Trips;
    }
    /// <summary>
    /// There are no comments for Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("UserName")]
    internal partial class Person : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="gender">Initial value of Gender.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Person CreatePerson(string userName, global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender gender)
        {
            Person person = new Person();
            person.UserName = userName;
            person.Gender = gender;
            return person;
        }
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "UserName is required.")]
        public virtual string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Gender is required.")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender _Gender;
        partial void OnGenderChanging(global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property Age in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::System.Nullable<long> Age
        {
            get
            {
                return this._Age;
            }
            set
            {
                this.OnAgeChanging(value);
                this._Age = value;
                this.OnAgeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<long> _Age;
        partial void OnAgeChanging(global::System.Nullable<long> value);
        partial void OnAgeChanged();
        /// <summary>
        /// There are no comments for Property HomeAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Location HomeAddress
        {
            get
            {
                return this._HomeAddress;
            }
            set
            {
                this.OnHomeAddressChanging(value);
                this._HomeAddress = value;
                this.OnHomeAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Location _HomeAddress;
        partial void OnHomeAddressChanging(global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Location value);
        partial void OnHomeAddressChanged();
        /// <summary>
        /// There are no comments for Property Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> Friends
        {
            get
            {
                return this._Friends;
            }
            set
            {
                this.OnFriendsChanging(value);
                this._Friends = value;
                this.OnFriendsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _Friends = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person>();
        partial void OnFriendsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> value);
        partial void OnFriendsChanged();
        /// <summary>
        /// There are no comments for Property Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> Trips
        {
            get
            {
                return this._Trips;
            }
            set
            {
                this.OnTripsChanging(value);
                this._Trips = value;
                this.OnTripsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> _Trips = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip>();
        partial void OnTripsChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> value);
        partial void OnTripsChanged();
    }
    /// <summary>
    /// There are no comments for AirlineSingle in the schema.
    /// </summary>
    internal partial class AirlineSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Airline>
    {
        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) { }

        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) { }

        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Airline> query)
            : base(query) { }

    }
    /// <summary>
    /// There are no comments for Airline in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AirlineCode
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("AirlineCode")]
    internal partial class Airline : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Airline object.
        /// </summary>
        /// <param name="airlineCode">Initial value of AirlineCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Airline CreateAirline(string airlineCode)
        {
            Airline airline = new Airline();
            airline.AirlineCode = airlineCode;
            return airline;
        }
        /// <summary>
        /// There are no comments for Property AirlineCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AirlineCode is required.")]
        public virtual string AirlineCode
        {
            get
            {
                return this._AirlineCode;
            }
            set
            {
                this.OnAirlineCodeChanging(value);
                this._AirlineCode = value;
                this.OnAirlineCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _AirlineCode;
        partial void OnAirlineCodeChanging(string value);
        partial void OnAirlineCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for AirportSingle in the schema.
    /// </summary>
    internal partial class AirportSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Airport>
    {
        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) { }

        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) { }

        /// <summary>
        /// Initialize a new AirportSingle object.
        /// </summary>
        public AirportSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Airport> query)
            : base(query) { }

    }
    /// <summary>
    /// There are no comments for Airport in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IcaoCode
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("IcaoCode")]
    internal partial class Airport : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Airport object.
        /// </summary>
        /// <param name="icaoCode">Initial value of IcaoCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Airport CreateAirport(string icaoCode)
        {
            Airport airport = new Airport();
            airport.IcaoCode = icaoCode;
            return airport;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property IcaoCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IcaoCode is required.")]
        public virtual string IcaoCode
        {
            get
            {
                return this._IcaoCode;
            }
            set
            {
                this.OnIcaoCodeChanging(value);
                this._IcaoCode = value;
                this.OnIcaoCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _IcaoCode;
        partial void OnIcaoCodeChanging(string value);
        partial void OnIcaoCodeChanged();
    }
    /// <summary>
    /// There are no comments for Location in the schema.
    /// </summary>
    internal partial class Location
    {
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.City City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.City _City;
        partial void OnCityChanging(global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.City value);
        partial void OnCityChanged();
    }
    /// <summary>
    /// There are no comments for City in the schema.
    /// </summary>
    internal partial class City
    {
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for TripSingle in the schema.
    /// </summary>
    internal partial class TripSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Trip>
    {
        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) { }

        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) { }

        /// <summary>
        /// Initialize a new TripSingle object.
        /// </summary>
        public TripSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Trip> query)
            : base(query) { }

    }
    /// <summary>
    /// There are no comments for Trip in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TripId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TripId")]
    internal partial class Trip : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Trip object.
        /// </summary>
        /// <param name="tripId">Initial value of TripId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Trip CreateTrip(int tripId)
        {
            Trip trip = new Trip();
            trip.TripId = tripId;
            return trip;
        }
        /// <summary>
        /// There are no comments for Property TripId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TripId is required.")]
        public virtual int TripId
        {
            get
            {
                return this._TripId;
            }
            set
            {
                this.OnTripIdChanging(value);
                this._TripId = value;
                this.OnTripIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _TripId;
        partial void OnTripIdChanging(int value);
        partial void OnTripIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for FlightSingle in the schema.
    /// </summary>
    internal partial class FlightSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Flight>
    {
        /// <summary>
        /// Initialize a new FlightSingle object.
        /// </summary>
        public FlightSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) { }

        /// <summary>
        /// Initialize a new FlightSingle object.
        /// </summary>
        public FlightSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) { }

        /// <summary>
        /// Initialize a new FlightSingle object.
        /// </summary>
        public FlightSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Flight> query)
            : base(query) { }

        /// <summary>
        /// There are no comments for Airline in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle Airline
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Airline == null))
                {
                    this._Airline = new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle(this.Context, GetPath("Airline"));
                }
                return this._Airline;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle _Airline;
        /// <summary>
        /// There are no comments for From in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle From
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._From == null))
                {
                    this._From = new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle(this.Context, GetPath("From"));
                }
                return this._From;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle _From;
        /// <summary>
        /// There are no comments for To in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle To
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._To == null))
                {
                    this._To = new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle(this.Context, GetPath("To"));
                }
                return this._To;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle _To;
    }
    /// <summary>
    /// There are no comments for Flight in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.EntityType()]
    internal partial class Flight : PublicTransportation
    {
        /// <summary>
        /// There are no comments for Property FlightNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual string FlightNumber
        {
            get
            {
                return this._FlightNumber;
            }
            set
            {
                this.OnFlightNumberChanging(value);
                this._FlightNumber = value;
                this.OnFlightNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FlightNumber;
        partial void OnFlightNumberChanging(string value);
        partial void OnFlightNumberChanged();
        /// <summary>
        /// There are no comments for Property Airline in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline Airline
        {
            get
            {
                return this._Airline;
            }
            set
            {
                this.OnAirlineChanging(value);
                this._Airline = value;
                this.OnAirlineChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline _Airline;
        partial void OnAirlineChanging(global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline value);
        partial void OnAirlineChanged();
        /// <summary>
        /// There are no comments for Property From in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport From
        {
            get
            {
                return this._From;
            }
            set
            {
                this.OnFromChanging(value);
                this._From = value;
                this.OnFromChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport _From;
        partial void OnFromChanging(global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport value);
        partial void OnFromChanged();
        /// <summary>
        /// There are no comments for Property To in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport To
        {
            get
            {
                return this._To;
            }
            set
            {
                this.OnToChanging(value);
                this._To = value;
                this.OnToChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport _To;
        partial void OnToChanging(global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport value);
        partial void OnToChanged();
    }
    /// <summary>
    /// There are no comments for EmployeeSingle in the schema.
    /// </summary>
    internal partial class EmployeeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Employee>
    {
        /// <summary>
        /// Initialize a new EmployeeSingle object.
        /// </summary>
        public EmployeeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) { }

        /// <summary>
        /// Initialize a new EmployeeSingle object.
        /// </summary>
        public EmployeeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) { }

        /// <summary>
        /// Initialize a new EmployeeSingle object.
        /// </summary>
        public EmployeeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Employee> query)
            : base(query) { }

        /// <summary>
        /// There are no comments for Peers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> Peers
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Peers == null))
                {
                    this._Peers = Context.CreateQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person>(GetPath("Peers"));
                }
                return this._Peers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _Peers;
        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> Friends
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Friends == null))
                {
                    this._Friends = Context.CreateQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person>(GetPath("Friends"));
                }
                return this._Friends;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _Friends;
        /// <summary>
        /// There are no comments for Trips in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> Trips
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Trips == null))
                {
                    this._Trips = Context.CreateQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip>(GetPath("Trips"));
                }
                return this._Trips;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> _Trips;
    }
    /// <summary>
    /// There are no comments for Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("UserName")]
    internal partial class Employee : Person
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="cost">Initial value of Cost.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Employee CreateEmployee(string userName, global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender gender, long cost)
        {
            Employee employee = new Employee();
            employee.UserName = userName;
            employee.Gender = gender;
            employee.Cost = cost;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property Cost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Cost is required.")]
        public virtual long Cost
        {
            get
            {
                return this._Cost;
            }
            set
            {
                this.OnCostChanging(value);
                this._Cost = value;
                this.OnCostChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private long _Cost;
        partial void OnCostChanging(long value);
        partial void OnCostChanged();
        /// <summary>
        /// There are no comments for Property Peers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> Peers
        {
            get
            {
                return this._Peers;
            }
            set
            {
                this.OnPeersChanging(value);
                this._Peers = value;
                this.OnPeersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _Peers = new global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person>();
        partial void OnPeersChanging(global::System.Collections.ObjectModel.Collection<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> value);
        partial void OnPeersChanged();
    }
    /// <summary>
    /// There are no comments for PersonGender in the schema.
    /// </summary>
    internal enum PersonGender
    {
        Male = 0,
        Female = 1,
        Unknow = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    internal static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="userName">The value of userName</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _source,
            string userName)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserName", userName }
            };
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="airlineCode">The value of airlineCode</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airline> _source,
            string airlineCode)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "AirlineCode", airlineCode }
            };
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirlineSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="icaoCode">The value of icaoCode</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Airport> _source,
            string icaoCode)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "IcaoCode", icaoCode }
            };
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.AirportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.TripSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.TripSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.TripSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.TripSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="tripId">The value of tripId</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.TripSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Trip> _source,
            int tripId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "TripId", tripId }
            };
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.TripSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PublicTransportation to its derived type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Flight
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.FlightSingle CastToFlight(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.PublicTransportation> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Flight> query = _source.CastTo<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Flight>();
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.FlightSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Employee as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Employee> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Employee as global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="userName">The value of userName</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Employee> _source,
            string userName)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserName", userName }
            };
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person to its derived type global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Employee
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle CastToEmployee(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Person> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Employee> query = _source.CastTo<global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.Employee>();
            return new global::Microsoft.OData.Service.Sample.TrippinInMemory.Models.EmployeeSingle(_source.Context, query.GetPath(null));
        }
    }
}
