//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 4/26/2023 8:52:46 PM
namespace Namespace1
{
    /// <summary>
    /// There are no comments for EntityContainer in the schema.
    /// </summary>
    public partial class EntityContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new EntityContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public EntityContainer(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new EntityContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public EntityContainer(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Set1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<EntityType> Set1
        {
            get
            {
                if ((this._Set1 == null))
                {
                    this._Set1 = base.CreateQuery<EntityType>("Set1");
                }
                return this._Set1;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<EntityType> _Set1;
        /// <summary>
        /// There are no comments for Set1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToSet1(EntityType entityType)
        {
            base.AddObject("Set1", entityType);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Namespace1"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""EntityType"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""BooleanPropFalse"" Type=""Edm.Boolean"" Nullable=""false"" DefaultValue=""False"" />
        <Property Name=""NullableBooleanPropFalse"" Type=""Edm.Boolean"" DefaultValue=""False"" />
        <Property Name=""BooleanPropTrue"" Type=""Edm.Boolean"" Nullable=""false"" DefaultValue=""True"" />
        <Property Name=""NullableBooleanPropTrue"" Type=""Edm.Boolean"" DefaultValue=""True"" />
        <Property Name=""IntProp"" Type=""Edm.Int32"" Nullable=""false"" DefaultValue=""50"" />
        <Property Name=""NullableIntProp"" Type=""Edm.Int32"" DefaultValue=""50"" />
        <Property Name=""SingleProp"" Type=""Edm.Single"" Nullable=""false"" DefaultValue=""50.2"" />
        <Property Name=""NullableSingleProp"" Type=""Edm.Single"" DefaultValue=""50.2"" />
        <Property Name=""SinglePropWithLetter"" Type=""Edm.Single"" Nullable=""false"" DefaultValue=""51.2f"" />
        <Property Name=""NullanleSinglePropWithLetter"" Type=""Edm.Single"" DefaultValue=""51.2f"" />
        <Property Name=""DoubleProp"" Type=""Edm.Double"" Nullable=""false"" DefaultValue=""52.2"" />
        <Property Name=""NullableDoubleProp"" Type=""Edm.Double"" DefaultValue=""52.2"" />
        <Property Name=""DecimalProp"" Type=""Edm.Decimal"" Nullable=""false"" DefaultValue=""53.2"" />
        <Property Name=""NullableDecimalProp"" Type=""Edm.Decimal"" DefaultValue=""53.2"" />
        <Property Name=""DecimalPropWithLetter"" Type=""Edm.Decimal"" Nullable=""false"" DefaultValue=""54.2m"" />
        <Property Name=""NullableDecimalPropWithLetter"" Type=""Edm.Decimal"" DefaultValue=""54.2m"" />
        <Property Name=""DateProp"" Type=""Edm.Date"" Nullable=""false"" DefaultValue=""2020-02-02"" />
        <Property Name=""NullableDateProp"" Type=""Edm.Date"" DefaultValue=""2020-02-02"" />
        <Property Name=""DateTimeOffsetProp"" Type=""Edm.DateTimeOffset"" Nullable=""false"" DefaultValue=""2020-02-02T22:44:00"" />
        <Property Name=""NullableDateTimeOffsetProp"" Type=""Edm.DateTimeOffset"" DefaultValue=""2020-02-02T22:44:00"" />
        <Property Name=""TimeOfDayProp"" Type=""Edm.TimeOfDay"" Nullable=""false"" DefaultValue=""22:44"" />
        <Property Name=""NullableTimeOfDayProp"" Type=""Edm.TimeOfDay"" DefaultValue=""22:44"" />
        <Property Name=""DurationProp"" Type=""Edm.Duration"" Nullable=""false"" DefaultValue=""P11DT23H59M59.999999999999S"" />
        <Property Name=""NullableDurationProp"" Type=""Edm.Duration"" DefaultValue=""P11DT23H59M59.999999999999S"" />
        <Property Name=""StringProp"" Type=""Edm.String"" Nullable=""false"" DefaultValue=""Foo"" />
        <Property Name=""NullableStringProp"" Type=""Edm.String"" DefaultValue=""Foo"" />
        <Property Name=""GuidProp"" Type=""Edm.Guid"" Nullable=""false"" DefaultValue=""123e4567-e89b-12d3-a456-426614174000"" />
        <Property Name=""NullableGuidProp"" Type=""Edm.Guid"" DefaultValue=""123e4567-e89b-12d3-a456-426614174000"" />
        <Property Name=""EnumProp"" Type=""Namespace1.SomeEnumType"" Nullable=""false"" DefaultValue=""EnumValue1"" />
        <Property Name=""NullableEnumProp"" Type=""Namespace1.SomeEnumType"" DefaultValue=""EnumValue1"" />
        <Property Name=""BinaryProp"" Type=""Edm.Binary"" Nullable=""false"" DefaultValue=""ab"" />
        <Property Name=""NullableBinaryProp"" Type=""Edm.Binary"" DefaultValue=""ab"" />
      </EntityType>
      <EnumType Name=""SomeEnumType"">
        <Member Name=""EnumVal1"" Value=""0"" />
        <Member Name=""EnumVal2"" Value=""1"" />
      </EnumType>
      <EntityContainer Name=""EntityContainer"">
        <EntitySet Name=""Set1"" EntityType=""Namespace1.EntityType"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

        }
    }
    /// <summary>
    /// There are no comments for EntityTypeSingle in the schema.
    /// </summary>
    public partial class EntityTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<EntityType>
    {
        /// <summary>
        /// Initialize a new EntityTypeSingle object.
        /// </summary>
        public EntityTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) { }

        /// <summary>
        /// Initialize a new EntityTypeSingle object.
        /// </summary>
        public EntityTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) { }

        /// <summary>
        /// Initialize a new EntityTypeSingle object.
        /// </summary>
        public EntityTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<EntityType> query)
            : base(query) { }

    }
    /// <summary>
    /// There are no comments for EntityType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class EntityType : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new EntityType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static EntityType CreateEntityType(int ID)
        {
            EntityType entityType = new EntityType();
            entityType.Id = ID;
            return entityType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property BooleanPropFalse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BooleanPropFalse is required.")]
        public virtual bool BooleanPropFalse
        {
            get
            {
                return this._BooleanPropFalse;
            }
            set
            {
                this.OnBooleanPropFalseChanging(value);
                this._BooleanPropFalse = value;
                this.OnBooleanPropFalseChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _BooleanPropFalse = false;
        partial void OnBooleanPropFalseChanging(bool value);
        partial void OnBooleanPropFalseChanged();
        /// <summary>
        /// There are no comments for Property NullableBooleanPropFalse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<bool> NullableBooleanPropFalse
        {
            get
            {
                return this._NullableBooleanPropFalse;
            }
            set
            {
                this.OnNullableBooleanPropFalseChanging(value);
                this._NullableBooleanPropFalse = value;
                this.OnNullableBooleanPropFalseChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _NullableBooleanPropFalse = false;
        partial void OnNullableBooleanPropFalseChanging(global::System.Nullable<bool> value);
        partial void OnNullableBooleanPropFalseChanged();
        /// <summary>
        /// There are no comments for Property BooleanPropTrue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BooleanPropTrue is required.")]
        public virtual bool BooleanPropTrue
        {
            get
            {
                return this._BooleanPropTrue;
            }
            set
            {
                this.OnBooleanPropTrueChanging(value);
                this._BooleanPropTrue = value;
                this.OnBooleanPropTrueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _BooleanPropTrue = true;
        partial void OnBooleanPropTrueChanging(bool value);
        partial void OnBooleanPropTrueChanged();
        /// <summary>
        /// There are no comments for Property NullableBooleanPropTrue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<bool> NullableBooleanPropTrue
        {
            get
            {
                return this._NullableBooleanPropTrue;
            }
            set
            {
                this.OnNullableBooleanPropTrueChanging(value);
                this._NullableBooleanPropTrue = value;
                this.OnNullableBooleanPropTrueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _NullableBooleanPropTrue = true;
        partial void OnNullableBooleanPropTrueChanging(global::System.Nullable<bool> value);
        partial void OnNullableBooleanPropTrueChanged();
        /// <summary>
        /// There are no comments for Property IntProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IntProp is required.")]
        public virtual int IntProp
        {
            get
            {
                return this._IntProp;
            }
            set
            {
                this.OnIntPropChanging(value);
                this._IntProp = value;
                this.OnIntPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _IntProp = 50;
        partial void OnIntPropChanging(int value);
        partial void OnIntPropChanged();
        /// <summary>
        /// There are no comments for Property NullableIntProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<int> NullableIntProp
        {
            get
            {
                return this._NullableIntProp;
            }
            set
            {
                this.OnNullableIntPropChanging(value);
                this._NullableIntProp = value;
                this.OnNullableIntPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _NullableIntProp = 50;
        partial void OnNullableIntPropChanging(global::System.Nullable<int> value);
        partial void OnNullableIntPropChanged();
        /// <summary>
        /// There are no comments for Property SingleProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SingleProp is required.")]
        public virtual float SingleProp
        {
            get
            {
                return this._SingleProp;
            }
            set
            {
                this.OnSinglePropChanging(value);
                this._SingleProp = value;
                this.OnSinglePropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private float _SingleProp = 50.2f;
        partial void OnSinglePropChanging(float value);
        partial void OnSinglePropChanged();
        /// <summary>
        /// There are no comments for Property NullableSingleProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<float> NullableSingleProp
        {
            get
            {
                return this._NullableSingleProp;
            }
            set
            {
                this.OnNullableSinglePropChanging(value);
                this._NullableSingleProp = value;
                this.OnNullableSinglePropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<float> _NullableSingleProp = 50.2f;
        partial void OnNullableSinglePropChanging(global::System.Nullable<float> value);
        partial void OnNullableSinglePropChanged();
        /// <summary>
        /// There are no comments for Property SinglePropWithLetter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SinglePropWithLetter is required.")]
        public virtual float SinglePropWithLetter
        {
            get
            {
                return this._SinglePropWithLetter;
            }
            set
            {
                this.OnSinglePropWithLetterChanging(value);
                this._SinglePropWithLetter = value;
                this.OnSinglePropWithLetterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private float _SinglePropWithLetter = 51.2f;
        partial void OnSinglePropWithLetterChanging(float value);
        partial void OnSinglePropWithLetterChanged();
        /// <summary>
        /// There are no comments for Property NullanleSinglePropWithLetter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<float> NullanleSinglePropWithLetter
        {
            get
            {
                return this._NullanleSinglePropWithLetter;
            }
            set
            {
                this.OnNullanleSinglePropWithLetterChanging(value);
                this._NullanleSinglePropWithLetter = value;
                this.OnNullanleSinglePropWithLetterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<float> _NullanleSinglePropWithLetter = 51.2f;
        partial void OnNullanleSinglePropWithLetterChanging(global::System.Nullable<float> value);
        partial void OnNullanleSinglePropWithLetterChanged();
        /// <summary>
        /// There are no comments for Property DoubleProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DoubleProp is required.")]
        public virtual double DoubleProp
        {
            get
            {
                return this._DoubleProp;
            }
            set
            {
                this.OnDoublePropChanging(value);
                this._DoubleProp = value;
                this.OnDoublePropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _DoubleProp = 52.2;
        partial void OnDoublePropChanging(double value);
        partial void OnDoublePropChanged();
        /// <summary>
        /// There are no comments for Property NullableDoubleProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<double> NullableDoubleProp
        {
            get
            {
                return this._NullableDoubleProp;
            }
            set
            {
                this.OnNullableDoublePropChanging(value);
                this._NullableDoubleProp = value;
                this.OnNullableDoublePropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _NullableDoubleProp = 52.2;
        partial void OnNullableDoublePropChanging(global::System.Nullable<double> value);
        partial void OnNullableDoublePropChanged();
        /// <summary>
        /// There are no comments for Property DecimalProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DecimalProp is required.")]
        public virtual decimal DecimalProp
        {
            get
            {
                return this._DecimalProp;
            }
            set
            {
                this.OnDecimalPropChanging(value);
                this._DecimalProp = value;
                this.OnDecimalPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _DecimalProp = 53.2m;
        partial void OnDecimalPropChanging(decimal value);
        partial void OnDecimalPropChanged();
        /// <summary>
        /// There are no comments for Property NullableDecimalProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<decimal> NullableDecimalProp
        {
            get
            {
                return this._NullableDecimalProp;
            }
            set
            {
                this.OnNullableDecimalPropChanging(value);
                this._NullableDecimalProp = value;
                this.OnNullableDecimalPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _NullableDecimalProp = 53.2m;
        partial void OnNullableDecimalPropChanging(global::System.Nullable<decimal> value);
        partial void OnNullableDecimalPropChanged();
        /// <summary>
        /// There are no comments for Property DecimalPropWithLetter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DecimalPropWithLetter is required.")]
        public virtual decimal DecimalPropWithLetter
        {
            get
            {
                return this._DecimalPropWithLetter;
            }
            set
            {
                this.OnDecimalPropWithLetterChanging(value);
                this._DecimalPropWithLetter = value;
                this.OnDecimalPropWithLetterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _DecimalPropWithLetter = 54.2m;
        partial void OnDecimalPropWithLetterChanging(decimal value);
        partial void OnDecimalPropWithLetterChanged();
        /// <summary>
        /// There are no comments for Property NullableDecimalPropWithLetter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<decimal> NullableDecimalPropWithLetter
        {
            get
            {
                return this._NullableDecimalPropWithLetter;
            }
            set
            {
                this.OnNullableDecimalPropWithLetterChanging(value);
                this._NullableDecimalPropWithLetter = value;
                this.OnNullableDecimalPropWithLetterChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _NullableDecimalPropWithLetter = 54.2m;
        partial void OnNullableDecimalPropWithLetterChanging(global::System.Nullable<decimal> value);
        partial void OnNullableDecimalPropWithLetterChanged();
        /// <summary>
        /// There are no comments for Property DateProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DateProp is required.")]
        public virtual global::Microsoft.OData.Edm.Date DateProp
        {
            get
            {
                return this._DateProp;
            }
            set
            {
                this.OnDatePropChanging(value);
                this._DateProp = value;
                this.OnDatePropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Edm.Date _DateProp = global::Microsoft.OData.Edm.Date.Parse("2020-02-02");
        partial void OnDatePropChanging(global::Microsoft.OData.Edm.Date value);
        partial void OnDatePropChanged();
        /// <summary>
        /// There are no comments for Property NullableDateProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.OData.Edm.Date> NullableDateProp
        {
            get
            {
                return this._NullableDateProp;
            }
            set
            {
                this.OnNullableDatePropChanging(value);
                this._NullableDateProp = value;
                this.OnNullableDatePropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.OData.Edm.Date> _NullableDateProp = global::Microsoft.OData.Edm.Date.Parse("2020-02-02");
        partial void OnNullableDatePropChanging(global::System.Nullable<global::Microsoft.OData.Edm.Date> value);
        partial void OnNullableDatePropChanged();
        /// <summary>
        /// There are no comments for Property DateTimeOffsetProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DateTimeOffsetProp is required.")]
        public virtual global::System.DateTimeOffset DateTimeOffsetProp
        {
            get
            {
                return this._DateTimeOffsetProp;
            }
            set
            {
                this.OnDateTimeOffsetPropChanging(value);
                this._DateTimeOffsetProp = value;
                this.OnDateTimeOffsetPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _DateTimeOffsetProp = global::System.DateTimeOffset.Parse("2020-02-02T22:44:00");
        partial void OnDateTimeOffsetPropChanging(global::System.DateTimeOffset value);
        partial void OnDateTimeOffsetPropChanged();
        /// <summary>
        /// There are no comments for Property NullableDateTimeOffsetProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::System.DateTimeOffset> NullableDateTimeOffsetProp
        {
            get
            {
                return this._NullableDateTimeOffsetProp;
            }
            set
            {
                this.OnNullableDateTimeOffsetPropChanging(value);
                this._NullableDateTimeOffsetProp = value;
                this.OnNullableDateTimeOffsetPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _NullableDateTimeOffsetProp = global::System.DateTimeOffset.Parse("2020-02-02T22:44:00");
        partial void OnNullableDateTimeOffsetPropChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnNullableDateTimeOffsetPropChanged();
        /// <summary>
        /// There are no comments for Property TimeOfDayProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TimeOfDayProp is required.")]
        public virtual global::Microsoft.OData.Edm.TimeOfDay TimeOfDayProp
        {
            get
            {
                return this._TimeOfDayProp;
            }
            set
            {
                this.OnTimeOfDayPropChanging(value);
                this._TimeOfDayProp = value;
                this.OnTimeOfDayPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Edm.TimeOfDay _TimeOfDayProp = global::Microsoft.OData.Edm.TimeOfDay.Parse("22:44");
        partial void OnTimeOfDayPropChanging(global::Microsoft.OData.Edm.TimeOfDay value);
        partial void OnTimeOfDayPropChanged();
        /// <summary>
        /// There are no comments for Property NullableTimeOfDayProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Microsoft.OData.Edm.TimeOfDay> NullableTimeOfDayProp
        {
            get
            {
                return this._NullableTimeOfDayProp;
            }
            set
            {
                this.OnNullableTimeOfDayPropChanging(value);
                this._NullableTimeOfDayProp = value;
                this.OnNullableTimeOfDayPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.OData.Edm.TimeOfDay> _NullableTimeOfDayProp = global::Microsoft.OData.Edm.TimeOfDay.Parse("22:44");
        partial void OnNullableTimeOfDayPropChanging(global::System.Nullable<global::Microsoft.OData.Edm.TimeOfDay> value);
        partial void OnNullableTimeOfDayPropChanged();
        /// <summary>
        /// There are no comments for Property DurationProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DurationProp is required.")]
        public virtual global::System.TimeSpan DurationProp
        {
            get
            {
                return this._DurationProp;
            }
            set
            {
                this.OnDurationPropChanging(value);
                this._DurationProp = value;
                this.OnDurationPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.TimeSpan _DurationProp = global::System.Xml.XmlConvert.ToTimeSpan("P11DT23H59M59.999999999999S");
        partial void OnDurationPropChanging(global::System.TimeSpan value);
        partial void OnDurationPropChanged();
        /// <summary>
        /// There are no comments for Property NullableDurationProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::System.TimeSpan> NullableDurationProp
        {
            get
            {
                return this._NullableDurationProp;
            }
            set
            {
                this.OnNullableDurationPropChanging(value);
                this._NullableDurationProp = value;
                this.OnNullableDurationPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.TimeSpan> _NullableDurationProp = global::System.Xml.XmlConvert.ToTimeSpan("P11DT23H59M59.999999999999S");
        partial void OnNullableDurationPropChanging(global::System.Nullable<global::System.TimeSpan> value);
        partial void OnNullableDurationPropChanged();
        /// <summary>
        /// There are no comments for Property StringProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "StringProp is required.")]
        public virtual string StringProp
        {
            get
            {
                return this._StringProp;
            }
            set
            {
                this.OnStringPropChanging(value);
                this._StringProp = value;
                this.OnStringPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _StringProp = "Foo";
        partial void OnStringPropChanging(string value);
        partial void OnStringPropChanged();
        /// <summary>
        /// There are no comments for Property NullableStringProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string NullableStringProp
        {
            get
            {
                return this._NullableStringProp;
            }
            set
            {
                this.OnNullableStringPropChanging(value);
                this._NullableStringProp = value;
                this.OnNullableStringPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NullableStringProp = "Foo";
        partial void OnNullableStringPropChanging(string value);
        partial void OnNullableStringPropChanged();
        /// <summary>
        /// There are no comments for Property GuidProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "GuidProp is required.")]
        public virtual global::System.Guid GuidProp
        {
            get
            {
                return this._GuidProp;
            }
            set
            {
                this.OnGuidPropChanging(value);
                this._GuidProp = value;
                this.OnGuidPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _GuidProp = global::System.Guid.Parse("123e4567-e89b-12d3-a456-426614174000");
        partial void OnGuidPropChanging(global::System.Guid value);
        partial void OnGuidPropChanged();
        /// <summary>
        /// There are no comments for Property NullableGuidProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::System.Guid> NullableGuidProp
        {
            get
            {
                return this._NullableGuidProp;
            }
            set
            {
                this.OnNullableGuidPropChanging(value);
                this._NullableGuidProp = value;
                this.OnNullableGuidPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _NullableGuidProp = global::System.Guid.Parse("123e4567-e89b-12d3-a456-426614174000");
        partial void OnNullableGuidPropChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnNullableGuidPropChanged();
        /// <summary>
        /// There are no comments for Property EnumProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EnumProp is required.")]
        public virtual global::Namespace1.SomeEnumType EnumProp
        {
            get
            {
                return this._EnumProp;
            }
            set
            {
                this.OnEnumPropChanging(value);
                this._EnumProp = value;
                this.OnEnumPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Namespace1.SomeEnumType _EnumProp = (global::Namespace1.SomeEnumType)global::System.Enum.Parse(global::System.Type.GetType("Namespace1.SomeEnumType"), "EnumValue1");
        partial void OnEnumPropChanging(global::Namespace1.SomeEnumType value);
        partial void OnEnumPropChanged();
        /// <summary>
        /// There are no comments for Property NullableEnumProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Nullable<global::Namespace1.SomeEnumType> NullableEnumProp
        {
            get
            {
                return this._NullableEnumProp;
            }
            set
            {
                this.OnNullableEnumPropChanging(value);
                this._NullableEnumProp = value;
                this.OnNullableEnumPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Namespace1.SomeEnumType> _NullableEnumProp = (global::System.Nullable<global::Namespace1.SomeEnumType>)global::System.Enum.Parse(global::System.Type.GetType("Namespace1.SomeEnumType"), "EnumValue1");
        partial void OnNullableEnumPropChanging(global::System.Nullable<global::Namespace1.SomeEnumType> value);
        partial void OnNullableEnumPropChanged();
        /// <summary>
        /// There are no comments for Property BinaryProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BinaryProp is required.")]
        public virtual byte[] BinaryProp
        {
            get
            {
                return this._BinaryProp;
            }
            set
            {
                this.OnBinaryPropChanging(value);
                this._BinaryProp = value;
                this.OnBinaryPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte[] _BinaryProp = System.Text.Encoding.UTF8.GetBytes("ab");
        partial void OnBinaryPropChanging(byte[] value);
        partial void OnBinaryPropChanged();
        /// <summary>
        /// There are no comments for Property NullableBinaryProp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual byte[] NullableBinaryProp
        {
            get
            {
                return this._NullableBinaryProp;
            }
            set
            {
                this.OnNullableBinaryPropChanging(value);
                this._NullableBinaryProp = value;
                this.OnNullableBinaryPropChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte[] _NullableBinaryProp = System.Text.Encoding.UTF8.GetBytes("ab");
        partial void OnNullableBinaryPropChanging(byte[] value);
        partial void OnNullableBinaryPropChanged();
    }
    /// <summary>
    /// There are no comments for SomeEnumType in the schema.
    /// </summary>
    public enum SomeEnumType
    {
        EnumVal1 = 0,
        EnumVal2 = 1
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Namespace1.EntityType as global::Namespace1.EntityTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Namespace1.EntityTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Namespace1.EntityType> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Namespace1.EntityTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Namespace1.EntityType as global::Namespace1.EntityTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Namespace1.EntityTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Namespace1.EntityType> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Namespace1.EntityTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
