'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 5/4/2020 7:15:45 PM
Namespace ODataDemo
    '''<summary>
    '''There are no comments for DemoService in the schema.
    '''</summary>
    Partial Public Class DemoService
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new DemoService object.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot, Global.System.Data.Services.Common.DataServiceProtocolVersion.V3)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.OnContextCreated
            Me.Format.LoadServiceModel = AddressOf GeneratedEdmModel.GetInstance
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(DemoService).Namespace.Remove(GetType(DemoService).Namespace.LastIndexOf("ODataDemo"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            Return clientType.FullName.Substring(ROOTNAMESPACE.Length)
        End Function
        '''<summary>
        '''There are no comments for Products in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Products() As Global.System.Data.Services.Client.DataServiceQuery(Of Product)
            Get
                If (Me._Products Is Nothing) Then
                    Me._Products = MyBase.CreateQuery(Of Product)("Products")
                End If
                Return Me._Products
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Products As Global.System.Data.Services.Client.DataServiceQuery(Of Product)
        '''<summary>
        '''There are no comments for ProductDetails in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property ProductDetails() As Global.System.Data.Services.Client.DataServiceQuery(Of ProductDetail)
            Get
                If (Me._ProductDetails Is Nothing) Then
                    Me._ProductDetails = MyBase.CreateQuery(Of ProductDetail)("ProductDetails")
                End If
                Return Me._ProductDetails
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ProductDetails As Global.System.Data.Services.Client.DataServiceQuery(Of ProductDetail)
        '''<summary>
        '''There are no comments for Categories in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Categories() As Global.System.Data.Services.Client.DataServiceQuery(Of Category)
            Get
                If (Me._Categories Is Nothing) Then
                    Me._Categories = MyBase.CreateQuery(Of Category)("Categories")
                End If
                Return Me._Categories
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Categories As Global.System.Data.Services.Client.DataServiceQuery(Of Category)
        '''<summary>
        '''There are no comments for Suppliers in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Suppliers() As Global.System.Data.Services.Client.DataServiceQuery(Of Supplier)
            Get
                If (Me._Suppliers Is Nothing) Then
                    Me._Suppliers = MyBase.CreateQuery(Of Supplier)("Suppliers")
                End If
                Return Me._Suppliers
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Suppliers As Global.System.Data.Services.Client.DataServiceQuery(Of Supplier)
        '''<summary>
        '''There are no comments for Persons in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Persons() As Global.System.Data.Services.Client.DataServiceQuery(Of Person)
            Get
                If (Me._Persons Is Nothing) Then
                    Me._Persons = MyBase.CreateQuery(Of Person)("Persons")
                End If
                Return Me._Persons
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Persons As Global.System.Data.Services.Client.DataServiceQuery(Of Person)
        '''<summary>
        '''There are no comments for PersonDetails in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property PersonDetails() As Global.System.Data.Services.Client.DataServiceQuery(Of PersonDetail)
            Get
                If (Me._PersonDetails Is Nothing) Then
                    Me._PersonDetails = MyBase.CreateQuery(Of PersonDetail)("PersonDetails")
                End If
                Return Me._PersonDetails
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PersonDetails As Global.System.Data.Services.Client.DataServiceQuery(Of PersonDetail)
        '''<summary>
        '''There are no comments for Advertisements in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Advertisements() As Global.System.Data.Services.Client.DataServiceQuery(Of Advertisement)
            Get
                If (Me._Advertisements Is Nothing) Then
                    Me._Advertisements = MyBase.CreateQuery(Of Advertisement)("Advertisements")
                End If
                Return Me._Advertisements
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Advertisements As Global.System.Data.Services.Client.DataServiceQuery(Of Advertisement)
        '''<summary>
        '''There are no comments for Products in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToProducts(ByVal product As Product)
            MyBase.AddObject("Products", product)
        End Sub
        '''<summary>
        '''There are no comments for ProductDetails in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToProductDetails(ByVal productDetail As ProductDetail)
            MyBase.AddObject("ProductDetails", productDetail)
        End Sub
        '''<summary>
        '''There are no comments for Categories in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToCategories(ByVal category As Category)
            MyBase.AddObject("Categories", category)
        End Sub
        '''<summary>
        '''There are no comments for Suppliers in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToSuppliers(ByVal supplier As Supplier)
            MyBase.AddObject("Suppliers", supplier)
        End Sub
        '''<summary>
        '''There are no comments for Persons in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToPersons(ByVal person As Person)
            MyBase.AddObject("Persons", person)
        End Sub
        '''<summary>
        '''There are no comments for PersonDetails in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToPersonDetails(ByVal personDetail As PersonDetail)
            MyBase.AddObject("PersonDetails", personDetail)
        End Sub
        '''<summary>
        '''There are no comments for Advertisements in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToAdvertisements(ByVal advertisement As Advertisement)
            MyBase.AddObject("Advertisements", advertisement)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private MustInherit Class GeneratedEdmModel
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared ParsedModel As Global.Microsoft.Data.Edm.IEdmModel = LoadModelFromString
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Const ModelPart0 As String = "<edmx:Edmx xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edmx"" Version=""1."& _ 
                "0""><edmx:DataServices xmlns:m=""http://schemas.microsoft.com/ado/2007/08/dataserv"& _ 
                "ices/metadata"" m:DataServiceVersion=""3.0"" m:MaxDataServiceVersion=""3.0""><Schema "& _ 
                "xmlns=""http://schemas.microsoft.com/ado/2009/11/edm"" Namespace=""ODataDemo""><Enti"& _ 
                "tyType Name=""Product""><Key><PropertyRef Name=""ID"" /></Key><Property Name=""ID"" Ty"& _ 
                "pe=""Edm.Int32"" Nullable=""false"" /><Property Name=""Name"" Type=""Edm.String"" m:FC_T"& _ 
                "argetPath=""SyndicationTitle"" m:FC_ContentKind=""text"" m:FC_KeepInContent=""false"" "& _ 
                "/><Property Name=""Description"" Type=""Edm.String"" m:FC_TargetPath=""SyndicationSum"& _ 
                "mary"" m:FC_ContentKind=""text"" m:FC_KeepInContent=""false"" /><Property Name=""Relea"& _ 
                "seDate"" Type=""Edm.DateTime"" Nullable=""false"" /><Property Name=""DiscontinuedDate"""& _ 
                " Type=""Edm.DateTime"" /><Property Name=""Rating"" Type=""Edm.Int16"" Nullable=""false"""& _ 
                " /><Property Name=""Price"" Type=""Edm.Double"" Nullable=""false"" /><NavigationProper"& _ 
                "ty Name=""Categories"" Relationship=""ODataDemo.Product_Categories_Category_Product"& _ 
                "s"" ToRole=""Category_Products"" FromRole=""Product_Categories"" /><NavigationPropert"& _ 
                "y Name=""Supplier"" Relationship=""ODataDemo.Product_Supplier_Supplier_Products"" To"& _ 
                "Role=""Supplier_Products"" FromRole=""Product_Supplier"" /><NavigationProperty Name="& _ 
                """ProductDetail"" Relationship=""ODataDemo.Product_ProductDetail_ProductDetail_Prod"& _ 
                "uct"" ToRole=""ProductDetail_Product"" FromRole=""Product_ProductDetail"" /></EntityT"& _ 
                "ype><EntityType Name=""FeaturedProduct"" BaseType=""ODataDemo.Product""><NavigationP"& _ 
                "roperty Name=""Advertisement"" Relationship=""ODataDemo.FeaturedProduct_Advertiseme"& _ 
                "nt_Advertisement_FeaturedProduct"" ToRole=""Advertisement_FeaturedProduct"" FromRol"& _ 
                "e=""FeaturedProduct_Advertisement"" /></EntityType><EntityType Name=""ProductDetail"& _ 
                """><Key><PropertyRef Name=""ProductID"" /></Key><Property Name=""ProductID"" Type=""Ed"& _ 
                "m.Int32"" Nullable=""false"" /><Property Name=""Details"" Type=""Edm.String"" /><Naviga"& _ 
                "tionProperty Name=""Product"" Relationship=""ODataDemo.Product_ProductDetail_Produc"& _ 
                "tDetail_Product"" ToRole=""Product_ProductDetail"" FromRole=""ProductDetail_Product"""& _ 
                " /></EntityType><EntityType Name=""Category"" OpenType=""true""><Key><PropertyRef Na"& _ 
                "me=""ID"" /></Key><Property Name=""ID"" Type=""Edm.Int32"" Nullable=""false"" /><Propert"& _ 
                "y Name=""Name"" Type=""Edm.String"" m:FC_TargetPath=""SyndicationTitle"" m:FC_ContentK"& _ 
                "ind=""text"" m:FC_KeepInContent=""true"" /><NavigationProperty Name=""Products"" Relat"& _ 
                "ionship=""ODataDemo.Product_Categories_Category_Products"" ToRole=""Product_Categor"& _ 
                "ies"" FromRole=""Category_Products"" /></EntityType><EntityType Name=""Supplier""><Ke"& _ 
                "y><PropertyRef Name=""ID"" /></Key><Property Name=""ID"" Type=""Edm.Int32"" Nullable="""& _ 
                "false"" /><Property Name=""Name"" Type=""Edm.String"" m:FC_TargetPath=""SyndicationTit"& _ 
                "le"" m:FC_ContentKind=""text"" m:FC_KeepInContent=""true"" /><Property Name=""Address"""& _ 
                " Type=""ODataDemo.Address"" /><Property Name=""Location"" Type=""Edm.GeographyPoint"" "& _ 
                "SRID=""Variable"" /><Property Name=""Concurrency"" Type=""Edm.Int32"" ConcurrencyMode="& _ 
                """Fixed"" Nullable=""false"" /><NavigationProperty Name=""Products"" Relationship=""ODa"& _ 
                "taDemo.Product_Supplier_Supplier_Products"" ToRole=""Product_Supplier"" FromRole=""S"& _ 
                "upplier_Products"" /></EntityType><ComplexType Name=""Address""><Property Name=""Str"& _ 
                "eet"" Type=""Edm.String"" /><Property Name=""City"" Type=""Edm.String"" /><Property Nam"& _ 
                "e=""State"" Type=""Edm.String"" /><Property Name=""ZipCode"" Type=""Edm.String"" /><Prop"& _ 
                "erty Name=""Country"" Type=""Edm.String"" /></ComplexType><EntityType Name=""Person"">"& _ 
                "<Key><PropertyRef Name=""ID"" /></Key><Property Name=""ID"" Type=""Edm.Int32"" Nullabl"& _ 
                "e=""false"" /><Property Name=""Name"" Type=""Edm.String"" /><NavigationProperty Name="""& _ 
                "PersonDetail"" Relationship=""ODataDemo.Person_PersonDetail_PersonDetail_Person"" T"& _ 
                "oRole=""PersonDetail_Person"" FromRole=""Person_PersonDetail"" /></EntityType><Entit"& _ 
                "yType Name=""Customer"" BaseType=""ODataDemo.Person""><Property Name=""TotalExpense"" "& _ 
                "Type=""Edm.Decimal"" Nullable=""false"" /></EntityType><EntityType Name=""Employee"" B"& _ 
                "aseType=""ODataDemo.Person""><Property Name=""EmployeeID"" Type=""Edm.Int64"" Nullable"& _ 
                "=""false"" /><Property Name=""HireDate"" Type=""Edm.DateTime"" Nullable=""false"" /><Pro"& _ 
                "perty Name=""Salary"" Type=""Edm.Single"" Nullable=""false"" /></EntityType><EntityTyp"& _ 
                "e Name=""PersonDetail""><Key><PropertyRef Name=""PersonID"" /></Key><Property Name="""& _ 
                "PersonID"" Type=""Edm.Int32"" Nullable=""false"" /><Property Name=""Age"" Type=""Edm.Byt"& _ 
                "e"" Nullable=""false"" /><Property Name=""Gender"" Type=""Edm.Boolean"" Nullable=""false"& _ 
                """ /><Property Name=""Phone"" Type=""Edm.String"" /><Property Name=""Address"" Type=""OD"& _ 
                "ataDemo.Address"" /><Property Name=""Photo"" Type=""Edm.Stream"" Nullable=""false"" /><"& _ 
                "NavigationProperty Name=""Person"" Relationship=""ODataDemo.Person_PersonDetail_Per"& _ 
                "sonDetail_Person"" ToRole=""Person_PersonDetail"" FromRole=""PersonDetail_Person"" />"& _ 
                "</EntityType><EntityType Name=""Advertisement"" m:HasStream=""true""><Key><PropertyR"& _ 
                "ef Name=""ID"" /></Key><Property Name=""ID"" Type=""Edm.Guid"" Nullable=""false"" /><Pro"& _ 
                "perty Name=""Name"" Type=""Edm.String"" /><Property Name=""AirDate"" Type=""Edm.DateTim"& _ 
                "e"" Nullable=""false"" /><NavigationProperty Name=""FeaturedProduct"" Relationship=""O"& _ 
                "DataDemo.FeaturedProduct_Advertisement_Advertisement_FeaturedProduct"" ToRole=""Fe"& _ 
                "aturedProduct_Advertisement"" FromRole=""Advertisement_FeaturedProduct"" /></Entity"& _ 
                "Type><Association Name=""Product_Categories_Category_Products""><End Type=""ODataDe"& _ 
                "mo.Category"" Role=""Category_Products"" Multiplicity=""*"" /><End Type=""ODataDemo.Pr"& _ 
                "oduct"" Role=""Product_Categories"" Multiplicity=""*"" /></Association><Association N"& _ 
                "ame=""Product_Supplier_Supplier_Products""><End Type=""ODataDemo.Supplier"" Role=""Su"& _ 
                "pplier_Products"" Multiplicity=""0..1"" /><End Type=""ODataDemo.Product"" Role=""Produ"& _ 
                "ct_Supplier"" Multiplicity=""*"" /></Association><Association Name=""Product_Product"& _ 
                "Detail_ProductDetail_Product""><End Type=""ODataDemo.ProductDetail"" Role=""ProductD"& _ 
                "etail_Product"" Multiplicity=""0..1"" /><End Type=""ODataDemo.Product"" Role=""Product"& _ 
                "_ProductDetail"" Multiplicity=""0..1"" /></Association><Association Name=""FeaturedP"& _ 
                "roduct_Advertisement_Advertisement_FeaturedProduct""><End Type=""ODataDemo.Adverti"& _ 
                "sement"" Role=""Advertisement_FeaturedProduct"" Multiplicity=""0..1"" /><End Type=""OD"& _ 
                "ataDemo.FeaturedProduct"" Role=""FeaturedProduct_Advertisement"" Multiplicity=""0..1"& _ 
                """ /></Association><Association Name=""Person_PersonDetail_PersonDetail_Person""><E"& _ 
                "nd Type=""ODataDemo.PersonDetail"" Role=""PersonDetail_Person"" Multiplicity=""0..1"" "& _ 
                "/><End Type=""ODataDemo.Person"" Role=""Person_PersonDetail"" Multiplicity=""0..1"" />"& _ 
                "</Association><EntityContainer Name=""DemoService"" m:IsDefaultEntityContainer=""tr"& _ 
                "ue""><EntitySet Name=""Products"" EntityType=""ODataDemo.Product"" /><EntitySet Name="& _ 
                """ProductDetails"" EntityType=""ODataDemo.ProductDetail"" /><EntitySet Name=""Categor"& _ 
                "ies"" EntityType=""ODataDemo.Category"" /><EntitySet Name=""Suppliers"" EntityType=""O"& _ 
                "DataDemo.Supplier"" /><EntitySet Name=""Persons"" EntityType=""ODataDemo.Person"" /><"& _ 
                "EntitySet Name=""PersonDetails"" EntityType=""ODataDemo.PersonDetail"" /><EntitySet "& _ 
                "Name=""Advertisements"" EntityType=""ODataDemo.Advertisement"" /><FunctionImport Nam"& _ 
                "e=""GetProductsByRating"" ReturnType=""Collection(ODataDemo.Product)"" EntitySet=""Pr"& _ 
                "oducts"" m:HttpMethod=""GET""><Parameter Name=""rating"" Type=""Edm.Int16"" Nullable=""f"& _ 
                "alse"" /></FunctionImport><FunctionImport Name=""Discount"" ReturnType=""Edm.Double"""& _ 
                " IsBindable=""true"" m:IsAlwaysBindable=""true""><Parameter Name=""product"" Type=""ODa"& _ 
                "taDemo.Product"" /><Parameter Name=""discountPercentage"" Type=""Edm.Int32"" Nullable"& _ 
                "=""false"" /></FunctionImport><FunctionImport Name=""IncreaseSalaries""><Parameter N"& _ 
                "ame=""percentage"" Type=""Edm.Int32"" Nullable=""false"" /></Func"
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Const ModelPart1 As String = "tionImport><AssociationSet Name=""Products_Advertisement_Advertisements"" Associati"& _ 
                "on=""ODataDemo.FeaturedProduct_Advertisement_Advertisement_FeaturedProduct""><End "& _ 
                "Role=""FeaturedProduct_Advertisement"" EntitySet=""Products"" /><End Role=""Advertise"& _ 
                "ment_FeaturedProduct"" EntitySet=""Advertisements"" /></AssociationSet><Association"& _ 
                "Set Name=""Products_Categories_Categories"" Association=""ODataDemo.Product_Categor"& _ 
                "ies_Category_Products""><End Role=""Product_Categories"" EntitySet=""Products"" /><En"& _ 
                "d Role=""Category_Products"" EntitySet=""Categories"" /></AssociationSet><Associatio"& _ 
                "nSet Name=""Products_Supplier_Suppliers"" Association=""ODataDemo.Product_Supplier_"& _ 
                "Supplier_Products""><End Role=""Product_Supplier"" EntitySet=""Products"" /><End Role"& _ 
                "=""Supplier_Products"" EntitySet=""Suppliers"" /></AssociationSet><AssociationSet Na"& _ 
                "me=""Products_ProductDetail_ProductDetails"" Association=""ODataDemo.Product_Produc"& _ 
                "tDetail_ProductDetail_Product""><End Role=""Product_ProductDetail"" EntitySet=""Prod"& _ 
                "ucts"" /><End Role=""ProductDetail_Product"" EntitySet=""ProductDetails"" /></Associa"& _ 
                "tionSet><AssociationSet Name=""Persons_PersonDetail_PersonDetails"" Association=""O"& _ 
                "DataDemo.Person_PersonDetail_PersonDetail_Person""><End Role=""Person_PersonDetail"& _ 
                """ EntitySet=""Persons"" /><End Role=""PersonDetail_Person"" EntitySet=""PersonDetails"& _ 
                """ /></AssociationSet></EntityContainer><Annotations Target=""ODataDemo.DemoServic"& _ 
                "e""><ValueAnnotation Term=""Org.OData.Display.V1.Description"" String=""This is a sa"& _ 
                "mple OData service with vocabularies"" /></Annotations><Annotations Target=""OData"& _ 
                "Demo.Product""><ValueAnnotation Term=""Org.OData.Display.V1.Description"" String=""A"& _ 
                "ll Products available in the online store"" /></Annotations><Annotations Target="""& _ 
                "ODataDemo.Product/Name""><ValueAnnotation Term=""Org.OData.Display.V1.DisplayName"""& _ 
                " String=""Product Name"" /></Annotations><Annotations Target=""ODataDemo.DemoServic"& _ 
                "e/Suppliers""><ValueAnnotation Term=""Org.OData.Publication.V1.PublisherName"" Stri"& _ 
                "ng=""Microsoft Corp."" /><ValueAnnotation Term=""Org.OData.Publication.V1.Publisher"& _ 
                "Id"" String=""MSFT"" /><ValueAnnotation Term=""Org.OData.Publication.V1.Keywords"" St"& _ 
                "ring=""Inventory, Supplier, Advertisers, Sales, Finance"" /><ValueAnnotation Term="& _ 
                """Org.OData.Publication.V1.AttributionUrl"" String=""http://www.odata.org/"" /><Valu"& _ 
                "eAnnotation Term=""Org.OData.Publication.V1.AttributionDescription"" String=""All r"& _ 
                "ights reserved"" /><ValueAnnotation Term=""Org.OData.Publication.V1.DocumentationU"& _ 
                "rl "" String=""http://www.odata.org/"" /><ValueAnnotation Term=""Org.OData.Publicati"& _ 
                "on.V1.TermsOfUseUrl"" String=""All rights reserved"" /><ValueAnnotation Term=""Org.O"& _ 
                "Data.Publication.V1.PrivacyPolicyUrl"" String=""http://www.odata.org/"" /><ValueAnn"& _ 
                "otation Term=""Org.OData.Publication.V1.LastModified"" String=""4/2/2013"" /><ValueA"& _ 
                "nnotation Term=""Org.OData.Publication.V1.ImageUrl "" String=""http://www.odata.org"& _ 
                "/"" /></Annotations></Schema></edmx:DataServices></edmx:Edmx>"
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function GetConcatenatedEdmxString() As String
                Return String.Concat(ModelPart0, ModelPart1)
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Public Shared Function GetInstance() As Global.Microsoft.Data.Edm.IEdmModel
                Return ParsedModel
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function LoadModelFromString() As Global.Microsoft.Data.Edm.IEdmModel
                Dim edmxToParse As String = GetConcatenatedEdmxString
                Dim reader As Global.System.Xml.XmlReader = CreateXmlReader(edmxToParse)
                Try 
                    Return Global.Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader)
                Finally
                    CType(reader,Global.System.IDisposable).Dispose
                End Try
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function CreateXmlReader(ByVal edmxToParse As String) As Global.System.Xml.XmlReader
                Return Global.System.Xml.XmlReader.Create(New Global.System.IO.StringReader(edmxToParse))
            End Function
        End Class
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.Product in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Name", Global.System.Data.Services.Common.SyndicationItemProperty.Title, Global.System.Data.Services.Common.SyndicationTextContentKind.Plaintext, false),  _
     Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Description", Global.System.Data.Services.Common.SyndicationItemProperty.Summary, Global.System.Data.Services.Common.SyndicationTextContentKind.Plaintext, false),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class Product
        '''<summary>
        '''Create a new Product object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="releaseDate">Initial value of ReleaseDate.</param>
        '''<param name="rating">Initial value of Rating.</param>
        '''<param name="price">Initial value of Price.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateProduct(ByVal ID As Integer, ByVal releaseDate As Date, ByVal rating As Short, ByVal price As Double) As Product
            Dim product As Product = New Product()
            product.ID = ID
            product.ReleaseDate = releaseDate
            product.Rating = rating
            product.Price = price
            Return product
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Description in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Description() As String
            Get
                Return Me._Description
            End Get
            Set
                Me.OnDescriptionChanging(value)
                Me._Description = value
                Me.OnDescriptionChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Description As String
        Partial Private Sub OnDescriptionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDescriptionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ReleaseDate in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ReleaseDate() As Date
            Get
                Return Me._ReleaseDate
            End Get
            Set
                Me.OnReleaseDateChanging(value)
                Me._ReleaseDate = value
                Me.OnReleaseDateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ReleaseDate As Date
        Partial Private Sub OnReleaseDateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnReleaseDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DiscontinuedDate in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DiscontinuedDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._DiscontinuedDate
            End Get
            Set
                Me.OnDiscontinuedDateChanging(value)
                Me._DiscontinuedDate = value
                Me.OnDiscontinuedDateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DiscontinuedDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnDiscontinuedDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnDiscontinuedDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Rating in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Rating() As Short
            Get
                Return Me._Rating
            End Get
            Set
                Me.OnRatingChanging(value)
                Me._Rating = value
                Me.OnRatingChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Rating As Short
        Partial Private Sub OnRatingChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnRatingChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Price in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Price() As Double
            Get
                Return Me._Price
            End Get
            Set
                Me.OnPriceChanging(value)
                Me._Price = value
                Me.OnPriceChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Price As Double
        Partial Private Sub OnPriceChanging(ByVal value As Double)
        End Sub
        Partial Private Sub OnPriceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Categories in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Categories() As Global.System.Collections.ObjectModel.Collection(Of Category)
            Get
                Return Me._Categories
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._Categories = value
                End If
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Categories As Global.System.Collections.ObjectModel.Collection(Of Category) = New Global.System.Collections.ObjectModel.Collection(Of Category)()
        '''<summary>
        '''There are no comments for Supplier in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Supplier() As Supplier
            Get
                Return Me._Supplier
            End Get
            Set
                Me._Supplier = value
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Supplier As Supplier
        '''<summary>
        '''There are no comments for ProductDetail in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ProductDetail() As ProductDetail
            Get
                Return Me._ProductDetail
            End Get
            Set
                Me._ProductDetail = value
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ProductDetail As ProductDetail
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.FeaturedProduct in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class FeaturedProduct
        Inherits Product
        '''<summary>
        '''Create a new FeaturedProduct object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="releaseDate">Initial value of ReleaseDate.</param>
        '''<param name="rating">Initial value of Rating.</param>
        '''<param name="price">Initial value of Price.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateFeaturedProduct(ByVal ID As Integer, ByVal releaseDate As Date, ByVal rating As Short, ByVal price As Double) As FeaturedProduct
            Dim featuredProduct As FeaturedProduct = New FeaturedProduct()
            featuredProduct.ID = ID
            featuredProduct.ReleaseDate = releaseDate
            featuredProduct.Rating = rating
            featuredProduct.Price = price
            Return featuredProduct
        End Function
        '''<summary>
        '''There are no comments for Advertisement in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Advertisement() As Advertisement
            Get
                Return Me._Advertisement
            End Get
            Set
                Me._Advertisement = value
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Advertisement As Advertisement
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.ProductDetail in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ProductID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ProductID")>  _
    Partial Public Class ProductDetail
        '''<summary>
        '''Create a new ProductDetail object.
        '''</summary>
        '''<param name="productID">Initial value of ProductID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateProductDetail(ByVal productID As Integer) As ProductDetail
            Dim productDetail As ProductDetail = New ProductDetail()
            productDetail.ProductID = productID
            Return productDetail
        End Function
        '''<summary>
        '''There are no comments for Property ProductID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ProductID() As Integer
            Get
                Return Me._ProductID
            End Get
            Set
                Me.OnProductIDChanging(value)
                Me._ProductID = value
                Me.OnProductIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ProductID As Integer
        Partial Private Sub OnProductIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnProductIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Details in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Details() As String
            Get
                Return Me._Details
            End Get
            Set
                Me.OnDetailsChanging(value)
                Me._Details = value
                Me.OnDetailsChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Details As String
        Partial Private Sub OnDetailsChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDetailsChanged()
        End Sub
        '''<summary>
        '''There are no comments for Product in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Product() As Product
            Get
                Return Me._Product
            End Get
            Set
                Me._Product = value
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Product As Product
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.Category in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Name", Global.System.Data.Services.Common.SyndicationItemProperty.Title, Global.System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class Category
        '''<summary>
        '''Create a new Category object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateCategory(ByVal ID As Integer) As Category
            Dim category As Category = New Category()
            category.ID = ID
            Return category
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Products in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Products() As Global.System.Collections.ObjectModel.Collection(Of Product)
            Get
                Return Me._Products
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._Products = value
                End If
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Products As Global.System.Collections.ObjectModel.Collection(Of Product) = New Global.System.Collections.ObjectModel.Collection(Of Product)()
    End Class
    '''<summary>
    '''There are no comments for ComplexType ODataDemo.Address in the schema.
    '''</summary>
    Partial Public Class Address
        '''<summary>
        '''There are no comments for Property Street in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Street() As String
            Get
                Return Me._Street
            End Get
            Set
                Me.OnStreetChanging(value)
                Me._Street = value
                Me.OnStreetChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Street As String
        Partial Private Sub OnStreetChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnStreetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property City in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property City() As String
            Get
                Return Me._City
            End Get
            Set
                Me.OnCityChanging(value)
                Me._City = value
                Me.OnCityChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _City As String
        Partial Private Sub OnCityChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCityChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property State in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property State() As String
            Get
                Return Me._State
            End Get
            Set
                Me.OnStateChanging(value)
                Me._State = value
                Me.OnStateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _State As String
        Partial Private Sub OnStateChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnStateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ZipCode in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ZipCode() As String
            Get
                Return Me._ZipCode
            End Get
            Set
                Me.OnZipCodeChanging(value)
                Me._ZipCode = value
                Me.OnZipCodeChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ZipCode As String
        Partial Private Sub OnZipCodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnZipCodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Country in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Country() As String
            Get
                Return Me._Country
            End Get
            Set
                Me.OnCountryChanging(value)
                Me._Country = value
                Me.OnCountryChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Country As String
        Partial Private Sub OnCountryChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCountryChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.Supplier in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Name", Global.System.Data.Services.Common.SyndicationItemProperty.Title, Global.System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class Supplier
        '''<summary>
        '''Create a new Supplier object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="concurrency">Initial value of Concurrency.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateSupplier(ByVal ID As Integer, ByVal concurrency As Integer) As Supplier
            Dim supplier As Supplier = New Supplier()
            supplier.ID = ID
            supplier.Concurrency = concurrency
            Return supplier
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Address in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Address() As Address
            Get
                If ((Me._Address Is Nothing)  _
                            AndAlso (Me._AddressInitialized <> true)) Then
                    Me._Address = New Address()
                    Me._AddressInitialized = true
                End If
                Return Me._Address
            End Get
            Set
                Me.OnAddressChanging(value)
                Me._Address = value
                Me._AddressInitialized = true
                Me.OnAddressChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Address As Address
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AddressInitialized As Boolean
        Partial Private Sub OnAddressChanging(ByVal value As Address)
        End Sub
        Partial Private Sub OnAddressChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Location in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Location() As Global.System.Spatial.GeographyPoint
            Get
                Return Me._Location
            End Get
            Set
                Me.OnLocationChanging(value)
                Me._Location = value
                Me.OnLocationChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Location As Global.System.Spatial.GeographyPoint
        Partial Private Sub OnLocationChanging(ByVal value As Global.System.Spatial.GeographyPoint)
        End Sub
        Partial Private Sub OnLocationChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Concurrency in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Concurrency() As Integer
            Get
                Return Me._Concurrency
            End Get
            Set
                Me.OnConcurrencyChanging(value)
                Me._Concurrency = value
                Me.OnConcurrencyChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Concurrency As Integer
        Partial Private Sub OnConcurrencyChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnConcurrencyChanged()
        End Sub
        '''<summary>
        '''There are no comments for Products in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Products() As Global.System.Collections.ObjectModel.Collection(Of Product)
            Get
                Return Me._Products
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    Me._Products = value
                End If
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Products As Global.System.Collections.ObjectModel.Collection(Of Product) = New Global.System.Collections.ObjectModel.Collection(Of Product)()
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.Person in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class Person
        '''<summary>
        '''Create a new Person object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreatePerson(ByVal ID As Integer) As Person
            Dim person As Person = New Person()
            person.ID = ID
            Return person
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Integer
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Integer
        Partial Private Sub OnIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for PersonDetail in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PersonDetail() As PersonDetail
            Get
                Return Me._PersonDetail
            End Get
            Set
                Me._PersonDetail = value
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PersonDetail As PersonDetail
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.Customer in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class Customer
        Inherits Person
        '''<summary>
        '''Create a new Customer object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="totalExpense">Initial value of TotalExpense.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateCustomer(ByVal ID As Integer, ByVal totalExpense As Decimal) As Customer
            Dim customer As Customer = New Customer()
            customer.ID = ID
            customer.TotalExpense = totalExpense
            Return customer
        End Function
        '''<summary>
        '''There are no comments for Property TotalExpense in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TotalExpense() As Decimal
            Get
                Return Me._TotalExpense
            End Get
            Set
                Me.OnTotalExpenseChanging(value)
                Me._TotalExpense = value
                Me.OnTotalExpenseChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TotalExpense As Decimal
        Partial Private Sub OnTotalExpenseChanging(ByVal value As Decimal)
        End Sub
        Partial Private Sub OnTotalExpenseChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.Employee in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class Employee
        Inherits Person
        '''<summary>
        '''Create a new Employee object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="employeeID">Initial value of EmployeeID.</param>
        '''<param name="hireDate">Initial value of HireDate.</param>
        '''<param name="salary">Initial value of Salary.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateEmployee(ByVal ID As Integer, ByVal employeeID As Long, ByVal hireDate As Date, ByVal salary As Single) As Employee
            Dim employee As Employee = New Employee()
            employee.ID = ID
            employee.EmployeeID = employeeID
            employee.HireDate = hireDate
            employee.Salary = salary
            Return employee
        End Function
        '''<summary>
        '''There are no comments for Property EmployeeID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property EmployeeID() As Long
            Get
                Return Me._EmployeeID
            End Get
            Set
                Me.OnEmployeeIDChanging(value)
                Me._EmployeeID = value
                Me.OnEmployeeIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _EmployeeID As Long
        Partial Private Sub OnEmployeeIDChanging(ByVal value As Long)
        End Sub
        Partial Private Sub OnEmployeeIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property HireDate in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property HireDate() As Date
            Get
                Return Me._HireDate
            End Get
            Set
                Me.OnHireDateChanging(value)
                Me._HireDate = value
                Me.OnHireDateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _HireDate As Date
        Partial Private Sub OnHireDateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnHireDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Salary in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Salary() As Single
            Get
                Return Me._Salary
            End Get
            Set
                Me.OnSalaryChanging(value)
                Me._Salary = value
                Me.OnSalaryChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Salary As Single
        Partial Private Sub OnSalaryChanging(ByVal value As Single)
        End Sub
        Partial Private Sub OnSalaryChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.PersonDetail in the schema.
    '''</summary>
    '''<KeyProperties>
    '''PersonID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.DataServiceKeyAttribute("PersonID")>  _
    Partial Public Class PersonDetail
        '''<summary>
        '''Create a new PersonDetail object.
        '''</summary>
        '''<param name="personID">Initial value of PersonID.</param>
        '''<param name="age">Initial value of Age.</param>
        '''<param name="gender">Initial value of Gender.</param>
        '''<param name="photo">Initial value of Photo.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreatePersonDetail(ByVal personID As Integer, ByVal age As Byte, ByVal gender As Boolean, ByVal photo As Global.System.Data.Services.Client.DataServiceStreamLink) As PersonDetail
            Dim personDetail As PersonDetail = New PersonDetail()
            personDetail.PersonID = personID
            personDetail.Age = age
            personDetail.Gender = gender
            personDetail.Photo = photo
            Return personDetail
        End Function
        '''<summary>
        '''There are no comments for Property PersonID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PersonID() As Integer
            Get
                Return Me._PersonID
            End Get
            Set
                Me.OnPersonIDChanging(value)
                Me._PersonID = value
                Me.OnPersonIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PersonID As Integer
        Partial Private Sub OnPersonIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnPersonIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Age in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Age() As Byte
            Get
                Return Me._Age
            End Get
            Set
                Me.OnAgeChanging(value)
                Me._Age = value
                Me.OnAgeChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Age As Byte
        Partial Private Sub OnAgeChanging(ByVal value As Byte)
        End Sub
        Partial Private Sub OnAgeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Gender in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Gender() As Boolean
            Get
                Return Me._Gender
            End Get
            Set
                Me.OnGenderChanging(value)
                Me._Gender = value
                Me.OnGenderChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Gender As Boolean
        Partial Private Sub OnGenderChanging(ByVal value As Boolean)
        End Sub
        Partial Private Sub OnGenderChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Phone in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Phone() As String
            Get
                Return Me._Phone
            End Get
            Set
                Me.OnPhoneChanging(value)
                Me._Phone = value
                Me.OnPhoneChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Phone As String
        Partial Private Sub OnPhoneChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPhoneChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Address in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Address() As Address
            Get
                If ((Me._Address Is Nothing)  _
                            AndAlso (Me._AddressInitialized <> true)) Then
                    Me._Address = New Address()
                    Me._AddressInitialized = true
                End If
                Return Me._Address
            End Get
            Set
                Me.OnAddressChanging(value)
                Me._Address = value
                Me._AddressInitialized = true
                Me.OnAddressChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Address As Address
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AddressInitialized As Boolean
        Partial Private Sub OnAddressChanging(ByVal value As Address)
        End Sub
        Partial Private Sub OnAddressChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Photo in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Photo() As Global.System.Data.Services.Client.DataServiceStreamLink
            Get
                Return Me._Photo
            End Get
            Set
                Me.OnPhotoChanging(value)
                Me._Photo = value
                Me.OnPhotoChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Photo As Global.System.Data.Services.Client.DataServiceStreamLink
        Partial Private Sub OnPhotoChanging(ByVal value As Global.System.Data.Services.Client.DataServiceStreamLink)
        End Sub
        Partial Private Sub OnPhotoChanged()
        End Sub
        '''<summary>
        '''There are no comments for Person in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Person() As Person
            Get
                Return Me._Person
            End Get
            Set
                Me._Person = value
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Person As Person
    End Class
    '''<summary>
    '''There are no comments for ODataDemo.Advertisement in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.HasStreamAttribute(),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class Advertisement
        '''<summary>
        '''Create a new Advertisement object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        '''<param name="airDate">Initial value of AirDate.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateAdvertisement(ByVal ID As Global.System.Guid, ByVal airDate As Date) As Advertisement
            Dim advertisement As Advertisement = New Advertisement()
            advertisement.ID = ID
            advertisement.AirDate = airDate
            Return advertisement
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AirDate in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AirDate() As Date
            Get
                Return Me._AirDate
            End Get
            Set
                Me.OnAirDateChanging(value)
                Me._AirDate = value
                Me.OnAirDateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AirDate As Date
        Partial Private Sub OnAirDateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnAirDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for FeaturedProduct in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property FeaturedProduct() As FeaturedProduct
            Get
                Return Me._FeaturedProduct
            End Get
            Set
                Me._FeaturedProduct = value
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _FeaturedProduct As FeaturedProduct
    End Class
End Namespace
